export const FETCH_API_TASK = "FETCH_API_TASK";
export const FETCH_API_TASK_SUCCESS = "FETCH_API_TASK_SUCCESS";
export const FETCH_API_TASK_ERR = "FETCH_API_TASK_SUCCESS";

export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS";
export const ADD_PRODUCTS_ERR = "ADD_PRODUCTS_ERR";

export const DEL_PRODUCT = "DEL_PRODUCT";
export const DEL_PRODUCT_SUCCESS = "DEL_PRODUCT_SUCCESS";
export const DEL_PRODUCT_ERR = "DEL_PRODUCT_ERR";

export const EDITTING = "EDITTING";
export const EDITTING_SUCCESS = "EDITTING_SUCCESS";
export const EDITTING_ERR = "EDITTING_ERR";

export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_PRODUCTS_SUCCESS = "UPDATE_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCTS_ERR = "UPDATE_PRODUCTS_ERR";
